"use client"
import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";
import Header from "@/components/header/page";
import { usePathname } from 'next/navigation';
export const metadata = {
  title: "web app cp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathName = usePathname()
  console.log("pathh",pathName)
  return (
    <html lang="en">
      <body>
        {pathName !== "/pages/login" && <Sidebar />}
        {children}
      </body>
    </html>
  );
}
